sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build MatCADAlgLinBook.tex
- makeindex _build/MatCADAlgLinBook.idx -s StyleInd.ist
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build MatCADAlgLinBook.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build MatCADAlgLinBook.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build MatCADAlgLin.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build MatCADAlgLin.tex

deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _build/MatCADAlgLinBook.pdf
  - _build/MatCADAlgLin.pdf
  skip_cleanup: true
  on:
    tags: true
